water: https://docs.google.com/spreadsheets/d/1mEi4Bd2YR63WD0j54FQ6QkzcUw_As9Wilue9kaXO2DE/edit?usp=sharing
sediment: https://docs.google.com/spreadsheets/d/1zc0bZdpl-Eoi35lI_5BGkElbscplyQRyNPLkSgeEyEQ/edit?usp=sharing
rocrate_profile_uri: https://data.emobon.embrc.eu/observatory-profile/0.1
data_quality_control_threshold_date: 2023-08-01
