on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download
        uses: emo-bon/logsheet-downloader-action@master
      - name: data-quality-control-action
        uses: emo-bon/data-quality-control-action@main
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ASSIGNEE: bulricht
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: workflow run
