on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *'
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      ROCRATE_PROFILE_URI: https://data.emobon.embrc.eu/observatory-profile/0.14
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download
        uses: emo-bon/logsheet-downloader-action@master
      - name: data-quality-control-action
        uses: emo-bon/data-quality-control-action@main
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ASSIGNEE: bulricht
      - name: rocrate-sembench-setup
        uses: vliz-be-opsci/rocrate-sembench-setup@main
        env:
          PROFILE: ${{ env.ROCRATE_PROFILE_URI }}
      - name: semantify
        uses: vliz-be-opsci/semantify@main
      - name: rocrate-metadata-generator-action
        uses: emo-bon/rocrate-metadata-generator-action@main
        env:
          PROFILE: ${{ env.ROCRATE_PROFILE_URI }}
          REPO: ${{ github.repository }}
      - name: rocrate-to-pages
        uses: vliz-be-opsci/rocrate-to-pages@latest
      - name: actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./unicornpages
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: workflow run
